name: buildroot
on:
    push:
        branches:
            - '*'
jobs:
    build-image:
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
        
          - name: Checkout submodules
            run: git submodule update --init --recursive

          - name: Checkout buildroot 2022.02.x
            run: |
                cd buildroot
                git checkout origin/2022.02.x

          - name: Create SSH key
            uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Build image
            env:
                GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./build.sh

          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
    # full-test:
    #    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    #    runs-on: self-hosted
    #    timeout-minutes: 120
    #    steps:
    #      - uses: actions/checkout@v2
    #      - name: Checkout submodules
    #        run: git submodule update --init --recursive
    #      - uses: webfactory/ssh-agent@v0.5.3
    #        with:
    #            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #      - name: Run full test
    #        env:
    #          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
    #        run: ./full-test.sh
    #      - name: Cleanup
    #        if: always()
    #        run: |
    #          ssh-add -D
