name: STM32 image
on:
    push:
        branches:
            - '*'
jobs:
    
    build-image:
        runs-on: self-hosted
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
        
          - name: Checkout submodules
            run: git submodule update --init --recursive

          - name: Build image
            uses: xanderhendriks/action-build-stm32cubeide@v10.0
            with:
              project-path: 'stm32cube/DummyModbusServer/STM32CubeIDE'
              project-target: 'DummyModbusServer/Debug'

          - name: Upload binary as artifact
            uses: actions/upload-artifact@v4
            with:
              name: DummyModbusServer_STM32C0
              path: stm32cube/DummyModbusServer/STM32CubeIDE/Debug/DummyModbusServer.elf

